-- Generated by nwg-displays on 2026-09-06 at 16:27:18. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@170.0",
    position = "1920x363",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.04",
    position = "0x576",
    scale = 1
})
